configs:
  cm:
    url: http://localhost:8443
    oidc.config: |
      name: Keycloak
      issuer: http://keycloak-keycloakx-http.keycloak.svc/auth/realms/gke-poc
      clientID: argocd
      clientSecretPath: /vault/secrets/oidc-secret
      requestedScopes: ["openid", "profile", "email", "groups"]
      requestedIDTokenClaims:
        groups:
          essential: true
  params:
    server.insecure: "true"
  rbac:
    policy.csv: |
      g, platform-admins, role:admin
      g, viewers, role:readonly
    policy.default: role:readonly

server:
  service:
    type: ClusterIP
  podAnnotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "argocd-server"
    vault.hashicorp.com/agent-inject-secret-oidc-secret: "secret/data/argocd-oidc"
    vault.hashicorp.com/agent-inject-template-oidc-secret: |
      {{- with secret "secret/data/argocd-oidc" -}}
      {{- index .Data.data "client-secret" -}}
      {{- end -}}
