apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev
  namespace: argocd
spec:
  description: Dev environment — GitOps project
  sourceRepos:
    - '*'
  destinations:
    - server: https://kubernetes.default.svc
      namespace: 'dev-*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

